name: AutoRecon Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y nikto nmap

      - name: Run AutoRecon
        run: |
          source venv/bin/activate
          chmod +x main.py
          ./main.py --target testphp.vulnweb.com

      # –– Upload step removed to avoid “Missing download info” error
      # - name: Upload Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: AutoRecon Report
      #     path: reports/
